### ISSUE TITLE
Dandori desktop doesn't display some levels.

### ISSUE THREAD

**Issue by applesaus88** [Chagrilled/P4-DandoriDesktop#2]
**Describe the bug**
Some levels don't get displayed.
Like Secluded Courtyard F01 and F02 don't get displayed, but F00 and F03 work fine.
Same with Kingdom of Beasts F04 doesn't get displayed and the other ones just work.

maps that don't work
area10
herostory010
herostory500
cave007_F01
cave007_F02
cave010_F04
cave012_F01
cave014_F00
cave014_F01
cave014_F02
cave014_F03
cave024_F00
cave035_F05
cave035_F09

**Comment by Chagrilled** [comment]
Define "the levels don't get displayed"? All the maps work fine for me. Have you correctly exported and decoded them all? Attaching a zip of your map files might help here.

![image](https://github.com/Chagrilled/P4-DandoriDesktop/assets/7968849/933e55e7-fb17-4053-adec-8260a48310f2)
![image](https://github.com/Chagrilled/P4-DandoriDesktop/assets/7968849/9e563340-240c-4e92-b567-43678a9fdf9c)

**Comment by applesaus88** [comment]
Weird, I decoded it 3 times and the same levels still don't display. (the level screen is completely black)

Maybe it is on my end since I run windows Arm version instead of 64-bit
