### ISSUE TITLE
Copy/Paste Entities

### ISSUE THREAD

**Issue by NeverTrustDrew** [Chagrilled/P4-DandoriDesktop#3]
I find the process of placing lots of entities very annoying. I propose that you are able to copy all the data about an entity and paste it. Just an idea to make the editor less tedious.

**Comment by Chagrilled** [comment]
Released in v1.0.2 - https://github.com/Chagrilled/P4-DandoriDesktop/commit/a1ffee1ecc174a2b3690ec0aadb78674f87cbda5
